import { Game, Vec2 } from '#game';

export default (game: Game) => {
	const scene = game.addScene('Cave', 8, 8);

	scene.setStartPos(new Vec2(3, 3));
	scene.getGrid().load([
		{ height: 0, type: 'cell', material: 7 },        
		{ height: 0, type: 'cell', material: 7 },        
		{ height: 0, type: 'cell', material: 7 },        
		{ height: 0, type: 'teleporter', material: 4, targetPos: { x: 5, y: 5 }, targetScene: 'Main' },        
		{ height: 0, type: 'cell', material: 7 },        
		{ height: 0, type: 'cell', material: 7 },        
		{ height: 0, type: 'cell', material: 7 },        
		{ height: 0, type: 'cell', material: 9 },        
		{ height: 0, type: 'cell', material: 7 },        
		{ height: 0, type: 'cell', material: 7 },        
		{ height: 0, type: 'cell', material: 1 },        
		{ height: 0, type: 'cell', material: 7 },        
		{ height: 0, type: 'cell', material: 2 },        
		{ height: 0, type: 'cell', material: 1 },        
		{ height: 0, type: 'cell', material: 7 },        
		{ height: 0, type: 'cell', material: 7 },        
		{ height: 0, type: 'cell', material: 8 },        
		{ height: 0, type: 'cell', material: 7 },        
		{ height: 0, type: 'cell', material: 7 },        
		{ height: 0, type: 'cell', material: 7 },        
		{ height: 0, type: 'cell', material: 7 },        
		{ height: 0, type: 'cell', material: 7 },        
		{ height: 0, type: 'cell', material: 1 },        
		{ height: 0, type: 'cell', material: 7 },        
		{ height: 0, type: 'cell', material: 8 },        
		{ height: 0, type: 'cell', material: 8 },        
		{ height: 0, type: 'cell', material: 7 },        
		{ height: 0, type: 'cell', material: 7 },        
		{ height: 0, type: 'cell', material: 1 },        
		{ height: 0, type: 'cell', material: 2 },        
		{ height: 0, type: 'cell', material: 7 },        
		{ height: 0, type: 'cell', material: 7 },        
		{ height: 0, type: 'cell', material: 2 },        
		{ height: 0, type: 'cell', material: 2 },        
		{ height: 0, type: 'cell', material: 7 },        
		{ height: 0, type: 'cell', material: 7 },        
		{ height: 0, type: 'cell', material: 7 },        
		{ height: 0, type: 'cell', material: 7 },        
		{ height: 0, type: 'cell', material: 7 },        
		{ height: 0, type: 'cell', material: 7 },        
		{ height: 0, type: 'cell', material: 3 },        
		{ height: 0, type: 'cell', material: 3 },        
		{ height: 0, type: 'cell', material: 1 },        
		{ height: 0, type: 'cell', material: 7 },        
		{ height: 0, type: 'cell', material: 7 },        
		{ height: 0, type: 'cell', material: 7 },        
		{ height: 0, type: 'cell', material: 7 },        
		{ height: 0, type: 'teleporter', material: 4, targetPos: { x: 0, y: 1 }, targetScene: 'Deep Cave' },        
		{ height: 0, type: 'cell', material: 3 },        
		{ height: 0, type: 'cell', material: 3 },        
		{ height: 0, type: 'cell', material: 3 },        
		{ height: 0, type: 'cell', material: 2 },        
		{ height: 0, type: 'cell', material: 1 },        
		{ height: 0, type: 'cell', material: 7 },        
		{ height: 0, type: 'cell', material: 9 },        
		{ height: 0, type: 'cell', material: 7 },        
		{ height: 0, type: 'cell', material: 3 },        
		{ height: 0, type: 'cell', material: 3 },        
		{ height: 0, type: 'cell', material: 3 },        
		{ height: 0, type: 'cell', material: 3 },        
		{ height: 0, type: 'cell', material: 2 },        
		{ height: 0, type: 'cell', material: 9 },        
		{ height: 0, type: 'cell', material: 7 },        
		{ height: 0, type: 'cell', material: 9 },
	]);
};
