import { Game, Vec2 } from '#game';

export default (game: Game): void => {
	const scene = game.addScene('City Centre', 12, 8);

	scene.setStartPos(new Vec2(3, 3));
	scene.getGrid().load([
		{ height: 0, type: 'cell', material: 6 },
		{ height: 0, type: 'cell', material: 6 },
		{ height: 0, type: 'cell', material: 6 },
		{ height: 0, type: 'cell', material: 5 },
		{ height: 0, type: 'cell', material: 5 },
		{ height: 0, type: 'cell', material: 5 },
		{ height: 0, type: 'cell', material: 5 },
		{ height: 0, type: 'cell', material: 6 },
		{ height: Infinity, type: 'cell', material: 15 },
		{ height: 0, type: 'cell', material: 6 },
		{ height: 0, type: 'cell', material: 6 },
		{ height: 0, type: 'cell', material: 6 },
		{ height: 0, type: 'cell', material: 6 },
		{ height: 0, type: 'cell', material: 6 },
		{ height: Infinity, type: 'cell', material: 17 },
		{ height: 0, type: 'cell', material: 6 },
		{ height: 0, type: 'cell', material: 6 },
		{ height: 0, type: 'cell', material: 5 },
		{ height: 0, type: 'cell', material: 6 },
		{ height: 0, type: 'cell', material: 6 },
		{ height: 0, type: 'cell', material: 6 },
		{ height: 0, type: 'cell', material: 6 },
		{ height: 0, type: 'cell', material: 6 },
		{ height: 0, type: 'cell', material: 6 },
		{ height: 0, type: 'cell', material: 6 },
		{ height: 0, type: 'cell', material: 6 },
		{ height: 0, type: 'cell', material: 6 },
		{ height: 0, type: 'cell', material: 6 },
		{ height: 0, type: 'cell', material: 6 },
		{ height: 0, type: 'cell', material: 6 },
		{ height: 0, type: 'cell', material: 6 },
		{ height: 0, type: 'cell', material: 6 },
		{ height: 0, type: 'cell', material: 6 },
		{ height: 0, type: 'cell', material: 6 },
		{ height: Infinity, type: 'cell', material: 13 },
		{ height: 0, type: 'cell', material: 6 },
		{ height: 0, type: 'teleporter', material: 4, targetPos: { x: 9, y: 2 }, targetScene: 'Main' },
		{ height: 0, type: 'cell', material: 5 },
		{ height: 0, type: 'cell', material: 6 },
		{ height: 0, type: 'cell', material: 6 },
		{ height: 0, type: 'cell', material: 6 },
		{ height: 0, type: 'cell', material: 6 },
		{ height: 0, type: 'cell', material: 6 },
		{ height: 0, type: 'cell', material: 6 },
		{ height: 0, type: 'cell', material: 6 },
		{ height: 0, type: 'cell', material: 6 },
		{ height: 0, type: 'cell', material: 6 },
		{ height: 0, type: 'cell', material: 6 },
		{ height: 0, type: 'teleporter', material: 4, targetPos: { x: 9, y: 3 }, targetScene: 'Main' },
		{ height: 0, type: 'cell', material: 5 },
		{ height: 0, type: 'cell', material: 5 },
		{ height: 0, type: 'cell', material: 6 },
		{ height: 0, type: 'cell', material: 6 },
		{ height: 0, type: 'cell', material: 6 },
		{ height: 0, type: 'cell', material: 6 },
		{ height: 0, type: 'cell', material: 6 },
		{ height: 0, type: 'cell', material: 6 },
		{ height: 0, type: 'cell', material: 6 },
		{ height: 0, type: 'cell', material: 5 },
		{ height: 0, type: 'cell', material: 5 },
		{ height: 0, type: 'cell', material: 5 },
		{ height: 0, type: 'cell', material: 5 },
		{ height: 0, type: 'cell', material: 5 },
		{ height: 0, type: 'cell', material: 5 },
		{ height: 0, type: 'cell', material: 6 },
		{ height: 0, type: 'cell', material: 6 },
		{ height: 0, type: 'cell', material: 6 },
		{ height: 0, type: 'cell', material: 6 },
		{ height: 0, type: 'cell', material: 6 },
		{ height: 0, type: 'cell', material: 5 },
		{ height: 0, type: 'cell', material: 5 },
		{ height: 0, type: 'cell', material: 5 },
		{ height: 0, type: 'cell', material: 5 },
		{ height: 0, type: 'cell', material: 5 },
		{ height: 0, type: 'cell', material: 14 },
		{ height: 0, type: 'cell', material: 6 },
		{ height: 0, type: 'cell', material: 6 },
		{ height: 0, type: 'cell', material: 6 },
		{ height: 0, type: 'cell', material: 6 },
		{ height: 0, type: 'cell', material: 5 },
		{ height: 0, type: 'cell', material: 16 },
		{ height: 0, type: 'cell', material: 5 },
		{ height: 0, type: 'cell', material: 5 },
		{ height: 0, type: 'cell', material: 5 },
		{ height: 0, type: 'cell', material: 5 },
		{ height: 0, type: 'cell', material: 5 },
		{ height: 0, type: 'cell', material: 5 },
		{ height: 0, type: 'cell', material: 6 },
		{ height: 0, type: 'cell', material: 6 },
		{ height: 0, type: 'cell', material: 6 },
		{ height: 0, type: 'cell', material: 5 },
		{ height: 0, type: 'cell', material: 5 },
		{ height: 0, type: 'cell', material: 5 },
		{ height: 0, type: 'cell', material: 5 },
		{ height: 0, type: 'cell', material: 5 },
		{ height: 0, type: 'cell', material: 5 },
	]);
};
