import { Game, Vec2 } from '#game';

export default (game: Game) => {
	const scene = game.addScene('City Centre', 12, 8);

	scene.setStartPos(new Vec2(3, 3));
	scene.getGrid().load([
		{ height: 0, type: 'cell', material: 6 },        
		{ height: 0, type: 'cell', material: 6 },        
		{ height: 0, type: 'cell', material: 6 },        
		{ height: 0, type: 'cell', material: 5 },        
		{ height: 0, type: 'cell', material: 5 },        
		{ height: 0, type: 'cell', material: 5 },        
		{ height: 0, type: 'cell', material: 5 },        
		{ height: 0, type: 'cell', material: 6 },        
		{ height: 0, type: 'cell', material: 6 },        
		{ height: 0, type: 'cell', material: 6 },        
		{ height: 0, type: 'cell', material: 6 },        
		{ height: 0, type: 'cell', material: 6 },        
		{ height: 0, type: 'cell', material: 6 },        
		{ height: 0, type: 'cell', material: 6 },        
		{ height: 0, type: 'cell', material: 6 },        
		{ height: 0, type: 'cell', material: 6 },        
		{ height: 0, type: 'cell', material: 6 },        
		{ height: 0, type: 'cell', material: 5 },        
		{ height: 0, type: 'cell', material: 6 },        
		{ height: 0, type: 'cell', material: 6 },        
		{ height: 0, type: 'cell', material: 6 },        
		{ height: 0, type: 'cell', material: 6 },        
		{ height: 0, type: 'cell', material: 6 },        
		{ height: 0, type: 'cell', material: 6 },        
		{ height: 0, type: 'cell', material: 6 },        
		{ height: 0, type: 'cell', material: 6 },        
		{ height: 0, type: 'cell', material: 6 },        
		{ height: 0, type: 'cell', material: 6 },        
		{ height: 0, type: 'cell', material: 6 },        
		{ height: 0, type: 'cell', material: 6 },        
		{ height: 0, type: 'cell', material: 6 },        
		{ height: 0, type: 'cell', material: 6 },        
		{ height: 0, type: 'cell', material: 6 },        
		{ height: 0, type: 'cell', material: 6 },        
		{ height: 0, type: 'cell', material: 6 },        
		{ height: 0, type: 'cell', material: 6 },        
		{ height: 0, type: 'teleporter', material: 4, targetPos: { x: 0, y: 0}, targetScene: 'Main' },        
		{ height: 0, type: 'cell', material: 5 },        
		{ height: 0, type: 'cell', material: 6 },        
		{ height: 0, type: 'cell', material: 6 },        
		{ height: 0, type: 'cell', material: 6 },        
		{ height: 0, type: 'cell', material: 6 },        
		{ height: 0, type: 'cell', material: 6 },        
		{ height: 0, type: 'cell', material: 6 },        
		{ height: 0, type: 'cell', material: 6 },        
		{ height: 0, type: 'cell', material: 6 },        
		{ height: 0, type: 'cell', material: 6 },        
		{ height: 0, type: 'cell', material: 6 },        
		{ height: 0, type: 'teleporter', material: 4, targetPos: { x: 0, y: 0}, targetScene: 'Main' },        
		{ height: 0, type: 'cell', material: 5 },        
		{ height: 0, type: 'cell', material: 5 },        
		{ height: 0, type: 'cell', material: 6 },        
		{ height: 0, type: 'cell', material: 6 },        
		{ height: 0, type: 'cell', material: 6 },        
		{ height: 0, type: 'cell', material: 6 },        
		{ height: 0, type: 'cell', material: 6 },        
		{ height: 0, type: 'cell', material: 6 },        
		{ height: 0, type: 'cell', material: 6 },        
		{ height: 0, type: 'cell', material: 5 },        
		{ height: 0, type: 'cell', material: 5 },        
		{ height: 0, type: 'cell', material: 5 },        
		{ height: 0, type: 'cell', material: 5 },        
		{ height: 0, type: 'cell', material: 5 },        
		{ height: 0, type: 'cell', material: 5 },        
		{ height: 0, type: 'cell', material: 6 },        
		{ height: 0, type: 'cell', material: 6 },        
		{ height: 0, type: 'cell', material: 6 },        
		{ height: 0, type: 'cell', material: 6 },        
		{ height: 0, type: 'cell', material: 6 },        
		{ height: 0, type: 'cell', material: 5 },        
		{ height: 0, type: 'cell', material: 5 },        
		{ height: 0, type: 'cell', material: 5 },        
		{ height: 0, type: 'cell', material: 5 },        
		{ height: 0, type: 'cell', material: 5 },        
		{ height: 0, type: 'cell', material: 5 },        
		{ height: 0, type: 'cell', material: 6 },        
		{ height: 0, type: 'cell', material: 6 },        
		{ height: 0, type: 'cell', material: 6 },        
		{ height: 0, type: 'cell', material: 6 },        
		{ height: 0, type: 'cell', material: 5 },        
		{ height: 0, type: 'cell', material: 5 },        
		{ height: 0, type: 'cell', material: 5 },        
		{ height: 0, type: 'cell', material: 5 },        
		{ height: 0, type: 'cell', material: 5 },        
		{ height: 0, type: 'cell', material: 5 },        
		{ height: 0, type: 'cell', material: 5 },        
		{ height: 0, type: 'cell', material: 5 },        
		{ height: 0, type: 'cell', material: 6 },        
		{ height: 0, type: 'cell', material: 6 },        
		{ height: 0, type: 'cell', material: 6 },        
		{ height: 0, type: 'cell', material: 5 },        
		{ height: 0, type: 'cell', material: 5 },        
		{ height: 0, type: 'cell', material: 5 },        
		{ height: 0, type: 'cell', material: 5 },        
		{ height: 0, type: 'cell', material: 5 },        
		{ height: 0, type: 'cell', material: 5 },
	]);
};
