import { Game, Vec2 } from '#game';

export default (game: Game): void => {
	const scene = game.addScene('Woods', 10, 9);

	scene.setStartPos(new Vec2(5, 4));
	scene.getGrid().load([
		{ height: 0, type: 'cell', material: 0 },        
		{ height: 0, type: 'cell', material: 0 },        
		{ height: 0, type: 'cell', material: 0 },        
		{ height: 0, type: 'cell', material: 2 },        
		{ height: 0, type: 'cell', material: 0 },        
		{ height: 0, type: 'cell', material: 0 },        
		{ height: 0, type: 'cell', material: 0 },        
		{ height: 0, type: 'cell', material: 0 },        
		{ height: 0, type: 'cell', material: 1 },        
		{ height: 0, type: 'cell', material: 0 },        
		{ height: 0, type: 'cell', material: 0 },        
		{ height: 0, type: 'cell', material: 1 },        
		{ height: 0, type: 'cell', material: 0 },        
		{ height: 0, type: 'cell', material: 0 },        
		{ height: 0, type: 'cell', material: 0 },        
		{ height: 0, type: 'cell', material: 0 },        
		{ height: 0, type: 'cell', material: 0 },        
		{ height: 0, type: 'cell', material: 2 },        
		{ height: 0, type: 'cell', material: 0 },        
		{ height: 0, type: 'cell', material: 0 },        
		{ height: 0, type: 'cell', material: 0 },        
		{ height: 0, type: 'cell', material: 0 },        
		{ height: 0, type: 'cell', material: 2 },        
		{ height: 0, type: 'cell', material: 0 },        
		{ height: 0, type: 'cell', material: 1 },        
		{ height: 0, type: 'cell', material: 0 },        
		{ height: 0, type: 'cell', material: 0 },        
		{ height: 0, type: 'cell', material: 0 },        
		{ height: 0, type: 'cell', material: 0 },        
		{ height: 0, type: 'cell', material: 2 },        
		{ height: 0, type: 'teleporter', material: 4, targetPos: { x: 10, y: 2 }, targetScene: 'Dark Woods' },        
		{ height: 0, type: 'cell', material: 0 },        
		{ height: 0, type: 'cell', material: 0 },        
		{ height: 0, type: 'cell', material: 0 },        
		{ height: 0, type: 'cell', material: 0 },        
		{ height: 0, type: 'cell', material: 0 },        
		{ height: 0, type: 'cell', material: 0 },        
		{ height: 0, type: 'cell', material: 0 },        
		{ height: 0, type: 'cell', material: 1 },        
		{ height: 0, type: 'cell', material: 0 },        
		{ height: 0, type: 'cell', material: 2 },        
		{ height: 0, type: 'cell', material: 0 },        
		{ height: 0, type: 'cell', material: 0 },        
		{ height: 0, type: 'cell', material: 0 },        
		{ height: 0, type: 'cell', material: 0 },        
		{ height: 0, type: 'cell', material: 0 },        
		{ height: 0, type: 'cell', material: 0 },        
		{ height: 0, type: 'cell', material: 2 },        
		{ height: 0, type: 'cell', material: 0 },        
		{ height: 0, type: 'cell', material: 0 },        
		{ height: 0, type: 'cell', material: 0 },        
		{ height: 0, type: 'cell', material: 0 },        
		{ height: 0, type: 'cell', material: 1 },        
		{ height: 0, type: 'cell', material: 0 },        
		{ height: 0, type: 'cell', material: 0 },        
		{ height: 0, type: 'cell', material: 0 },        
		{ height: 0, type: 'cell', material: 0 },        
		{ height: 0, type: 'cell', material: 0 },        
		{ height: 0, type: 'cell', material: 0 },        
		{ height: 0, type: 'cell', material: 0 },        
		{ height: 0, type: 'cell', material: 0 },        
		{ height: 0, type: 'cell', material: 0 },        
		{ height: 0, type: 'cell', material: 0 },        
		{ height: 0, type: 'cell', material: 0 },        
		{ height: 0, type: 'cell', material: 2 },        
		{ height: 0, type: 'cell', material: 0 },        
		{ height: 0, type: 'cell', material: 0 },        
		{ height: 0, type: 'cell', material: 1 },        
		{ height: 0, type: 'cell', material: 0 },        
		{ height: 0, type: 'cell', material: 0 },        
		{ height: 0, type: 'cell', material: 1 },        
		{ height: 0, type: 'cell', material: 0 },        
		{ height: 0, type: 'cell', material: 0 },        
		{ height: 0, type: 'cell', material: 0 },        
		{ height: 0, type: 'cell', material: 0 },        
		{ height: 0, type: 'cell', material: 0 },        
		{ height: 0, type: 'cell', material: 0 },        
		{ height: 0, type: 'cell', material: 0 },        
		{ height: 0, type: 'cell', material: 0 },        
		{ height: 0, type: 'cell', material: 2 },        
		{ height: 0, type: 'cell', material: 0 },        
		{ height: 0, type: 'cell', material: 2 },        
		{ height: 0, type: 'cell', material: 0 },        
		{ height: 0, type: 'cell', material: 0 },        
		{ height: 0, type: 'cell', material: 0 },        
		{ height: 0, type: 'cell', material: 0 },        
		{ height: 0, type: 'teleporter', material: 4, targetPos: { x: 6, y: 0 }, targetScene: 'Main' },        
		{ height: 0, type: 'cell', material: 0 },        
		{ height: 0, type: 'cell', material: 0 },        
		{ height: 0, type: 'cell', material: 0 },
	]);
};
